### ISSUE TITLE
Fix mediatek boot 

### ISSUE THREAD

**Issue by walker425** [YukiMetaa/treble_apollo#3]
I would love to experience this Rom but unfortunately it can't boot on mediatek devices, please it would be great if it's fixed.

**Comment by YukiMetaa** [comment]
I use trebledroid and the rest is edited by hand, not much changed in the original source, but mostly I make adjustments in the device tree

**Comment by YukiMetaa** [comment]
make permissive selinux
[Permissiver_v5.zip](https://github.com/YukiMetaa/treble_apollo/files/14634151/Permissiver_v5.zip)
